name: Update JSON on file push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run script to update JSON
      working-directory: ./ostravskypinec
      run: python scripts/update_json.py

    - name: Commit and push if it changed
      working-directory: ./ostravskypinec
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data.json
        git diff --staged --quiet || git commit -m "Automated update of data.json"
        git push